### ISSUE TITLE
Shows internal server error

### ISSUE THREAD

**Issue by Neel7317** [aws-samples/ai-video-super-resolution#1]
after launch solution in AWS global region. and after uploaded video in s3 bucket with file name 1.mp4
try to run following code and its throwing internal server error..

import requests
import json

url='https://65ab94bo5e.execute-api.us-west-2.amazonaws.com/prod/'

payload = json.dumps({
 "key": "1.mp4"
})

headers = {
 'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)
print(response.text)

**Comment by xiaotinghe** [comment]
Can you send me the logs of AWS lambda?

**Comment by Neel7317** [comment]
This is what i found in AWS logs..

[ERROR] TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/var/task/split.py", line 45, in handler
    key = body['key']

**Comment by Neel7317** [comment]
![screenshot](https://user-images.githubusercontent.com/65647192/142139677-2ab8479d-4bb5-4614-894f-2d28eabf5f12.png)

**Comment by jonashogstrom** [comment]
I failed using the sample events, but changing the event to look like this:
{
  "body": {
    "key": "MyVideo.mp4",
    "scale": "4",
    "task": "inference"
  }
}
at least it start processing

**Comment by Neel7317** [comment]
Is it successfully executed? i mean video convert to high resolution or not??

**Comment by jonashogstrom** [comment]
I have successfully converted a video in 360x240 with x4, and a full HD video to 4k, the results in level of detail is actually impressive. Motion blur and weak colors stay the same. Processing time was 25 minutes for 12 seconds of full HD video so I would say that cost wise it will be hard to justify. Collecting better quality video from the beginning should probably be your first option.

**Comment by ajeema** [comment]
I'm experiencing the same issue. Tried modifying as suggested above with no luck. Please advise

**Comment by ajeema** [comment]
the error is:
`[ERROR] TypeError: 'NoneType' object is not subscriptable Traceback (most recent call last):   File "/var/task/split.py", line 42, in handler     key = body['key']`

**Comment by Windsooon** [comment]
@jonashogstrom Can you tell us how to make this template work? Did you deploy it using AWS CloudFormation or Follow the steps at Readme.md? I also got an internal server error, we need to auth before sending any requests.

**Comment by jonashogstrom** [comment]
@Windsooon As far as I remember, the changes I mentioned in my post above from feb 8, 2022 was sufficient for me. I have since removed all traces of this experiment from my AWS account, so I can't check any details I'm afraid. To be honest, I don't remember how I set it up.
